#' Source and store objects as list
#' 
#' Executes the code provided in a given connection (file or URL) or list of connections and stores all generated objects in a named list.
#' Useful, for instance, to get a list of functions defined in one or more external scripts.
#'
#' @param files The file or a list/vector of files passed to the `file` argument of `source`.
#' @param sorted Sort objects by name or keep in order of generation?
#' @param only.functions Whether only functions or also other objects generated by the code should be returned
#' @param ... Further arguments passed to `source`. This must not contain the argument `local`!
#'
#' @return A named list of objects, possibly sorted by name, optionally excluding all non-functions.
#' 
#' @details
#' If `files` is a vector (including lists) with more than 1 element, each of the elements is passed to `scource` consecutively.
#' 
#' According to the documentation of `base::source`, the `file` argument is: a connection or a character string giving the pathname of the file or URL to read from. "" indicates the connection `stdin()`.
#' 
#' 
#' @export
source_to_list <- function(files, sorted = TRUE, only.functions = FALSE, ...) {
  e <- new.env()
  if (is.vector(files) & length(files) > 1) {
    for (f in files) source(f, local = e, ...)
  } else {
    source(files, local = e, ...)
  }
  if (only.functions) l <- l[sapply(l, is.function)]
  as.list(e, sorted = sorted)
}