#' Source a file and store store objects in a list
#' 
#' This is a wrapper around `source`. It is mainly useful to produce a list of functions when several functions are defined in one file.
#'
#' @param file Path to file to be sourced.
#' @param only.functions Whether only functions or also other objects generated by the code should be returned (defaults to `TRUE`).
#' @param ... Other arguments to be passed to `source()`.
#'
#' @return A list of all objects generated by the sourced code. If `only.functions = TRUE`, then other objects than functions are removed.
#' 
#' @export
source_to_list <- function(file, only.functions = TRUE, ...) {
  l <- new.env()
  source(file, local = l, ...)
  l <- as.list(l)
  if (only.functions) l <- l[sapply(l, is.function)]
  return(l)
}