#' Custom functions for DB interactions
#' 
#' `connect_itembank`, `connect_checkausw` and `connect_checkdatarev` are wrappers around `RMariaDB::dbConnect` that include the host and port needed to access our DBs.
#' `dbDataTypes` gets the data storage types and - if chosen - the character lengths of each column.
#' 
#' @param user The username as a string.
#' @param pw The password as a string. If `NULL`, the default, a pop-up appears to ask for the password.
#' @param con A database connection object, as generated by `connect_itembank` or `dbConnect`.
#' @param tab The name of a table in the database, as a string.
#' @param incl_length Logical, whether to include the maximum character length of each column.
#' @param string_only Logical, whether to filter the output for columns of type `string` only.
#' 
#' @return For `connect_itembank` and `connect_checkbank`, a database connection object, class `MariaDBConnection`. For `dbDataTypes` a data.frame with one row per column in the database table.
#' 
#' @name connect_itembank
#' @export
connect_itembank <- function(user, pw = NULL) {
  require(RMariaDB)
  if (is.null(pw)) {
    pw <- rstudioapi::askForPassword(paste("Itembase password for", user))
  }
  dbConnect(
    drv = MariaDB(), 
    dbname = "itembank",
    username = user,
    password = pw, 
    host = "192.168.1.103", 
    port = 3306
  )
}

#' @name connect_itembank
#' @export
connect_checkausw <- function(user, pw = NULL) {
  require(RMariaDB)
  if (is.null(pw)) {
    pw <- rstudioapi::askForPassword(paste("Itembase password for", 
                                           user))
  }
  dbConnect(
    drv = MariaDB(),
    dbname = "checkauswertung",
    username = user, 
    password = pw,
    host = "192.168.1.103",
    port = 3306
  )
}

#' @name connect_itembank
#' @export
connect_checkdatarev <- function(user, pw = NULL, cert_path = NULL) {
  require(RMariaDB)
  if (is.null(pw)) {
    pw <- rstudioapi::askForPassword(paste("Itembase password for", 
                                           user))
  }
  if (is.null(cert_path)) {
    trypaths <- c(paste0("C:/Users/",Sys.info()["user"],"/ibedb-prod-ca.pem"),
                  paste0("C:/Users/",Sys.info()["user"],"/Documents/ibedb-prod-ca.pem"),
                  paste0("C:/Users/",Sys.info()["user"],"/kDrive/ibedb-prod-ca.pem"),
                  paste0("C:/Users/",Sys.info()["user"],"/Documents/kDrive/ibedb-prod-ca.pem"))
    if (any(file.exists(trypaths))) {
      cert_path <- trypaths[which(file.exists(trypaths))[1]]
    } else {
      stop("No SLL certificate file (PEM) found. Please specify path manually or move file to ",paste0("C:/Users/",Sys.info()["user"],"/ibedb-prod-ca.pem"))
    }
  }
  conn <- dbConnect(
    drv = MariaDB(),
    dbname = "check_data_revisions",
    username = user, 
    password = pw,
    ssl.ca = cert_path,
    host = "ibedb-exoscale-a9317092-eb47-4f96-875c-c8641b2337e7.a.aivencloud.com",
    port = 21699
  )
}

#' @name connect_itembank
#' @export
dbDataTypes <- function(con, tab, incl_length = TRUE, string_only = FALSE) {
  require(RMariaDB)
  qr <- dbSendQuery(con, paste0("SELECT * FROM ",tab,";")) # execute SELECT serverside
  cols <- RMariaDB::dbColumnInfo(qr) # get column types
  dbClearResult(qr) # clear result set serverside
  if (incl_length) {
    lens <- RMariaDB::dbGetQuery(con,
                                 paste0("SELECT ",
                                        paste0("MAX(Char_Length(",cols[,1],")) ",cols[,1], collapse = ", "),
                                        " FROM ",tab,";"))
    lens <- sapply(lens, as.double)
    cols$length <- lens
  }
  if (string_only) cols <- cols[cols[[2]]=="string", ]
  return(cols)
}
