#' Custom functions for itembank interactions
#' 
#' `connect_itembank` is a wrapper around `RMariaDB::dbConnect` that includes the host and port needed to access our itembank.
#' `dbDataTypes` gets the data storage types and - if chosen - the character lengths of each column.
#' 
#' @param user The username as a string.
#' @param pw The password as a string. If `NULL`, the default, a pop-up appears to ask for the password.
#' @param con A database connection object, as generated by `connect_itembank` or `dbConnect`.
#' @param tab The name of a table in the database, as a string.
#' @param incl_length Logical, whether to include the maximum character length of each column.
#' @param string_only Logical, whether to filter the output for columns of type `string` only.
#' 
#' @return For `connect_itembank`, a database connection object, class `MariaDBConnection`. For `dbDataTypes` a data.frame with one row per column in the database table.
#' 
#' @export
connect_itembank <- function(user, pw = NULL) {
  require(RMariaDB)
  if (is.null(pw)) {
    pw <- rstudioapi::askForPassword(paste("Itembase password for", user))
  }
  dbConnect(
    drv = MariaDB(), 
    dbname = "itembank",
    username = user,
    password = pw, 
    host = "192.168.1.103", 
    port = 3306
  )
}

#' @export
dbDataTypes <- function(con, tab, incl_length = TRUE, string_only = FALSE) {
  require(RMariaDB)
  qr <- dbSendQuery(con, paste0("SELECT * FROM ",tab,";")) # execute SELECT serverside
  cols <- RMariaDB::dbColumnInfo(qr) # get column types
  dbClearResult(qr) # clear result set serverside
  if (incl_length) {
    lens <- RMariaDB::dbGetQuery(con,
                                 paste0("SELECT ",
                                        paste0("MAX(Char_Length(",cols[,1],")) ",cols[,1], collapse = ", "),
                                        " FROM ",tab,";"))
    lens <- sapply(lens, as.double)
    cols$length <- lens
  }
  if (string_only) cols <- cols[cols[[2]]=="string", ]
  return(cols)
}
